### ISSUE TITLE
Message redaction feature

### ISSUE THREAD

**Issue by hlascelles** [TheDesignium/cdk-log-notifier#1]
We would like to use this to notify on various errors/events, but we know they may contain [Personally identifiable information](https://en.wikipedia.org/wiki/Personal_data).

Would you be open to a change that would apply (say) a regex group match to extract the part of the message we'd like to notify?

Great project, thank you!

**Comment by acomagu** [comment]
Thank you for feedback for this project!

That feature suggestion sounds great. I will work on it as soon as my time is free.

**Comment by hlascelles** [comment]
Terrific, thank you! :bow:

**Comment by acomagu** [comment]
@hlascelles Hi, enabling [the builtin masking feature of CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch-logs-data-protection-policies.html) seems to effect the Slack posts from cdk-log-notifier.

Does this solution work for you?

![image](https://github.com/TheDesignium/cdk-log-notifier/assets/1362750/842409d5-766d-406e-9508-d156e96e3659)

**Comment by hlascelles** [comment]
Ah interesting... I will take a look!
